<h2>Login using this form</h2>

<?php echo $this->tag->form("login/verify"); ?>

    <p>
        <label for="name">Email</label>
        <?php echo $this->tag->emailField("email"); ?>
    </p>

    <p>
        <label for="email">Password</label>
        <?php echo $this->tag->passwordField("password"); ?>
    </p>
        
    <p>
        <?php echo $this->tag->submitButton("Login"); ?>
    </p>