<h2>Login using this form</h2>

<?php echo $this->tag->form("login/register"); ?>

    <p>
        <label for="name">Email</label>
        <?php echo $this->tag->textField("email"); ?>
    </p>

    <p>
        <label for="email">Password</label>
        <?php echo $this->tag->textField("password"); ?>

        <p>
        <?php echo $this->tag->submitButton("Login"); ?>
    </p>
    </p>