<h2>Login using this form</h2>

<?php echo $this->tag->form("login/register"); ?>

    <p>
        <label for="name">Email</label>
        <?php echo $this->tag->textField("email"); ?>
    </p>

    <p>
        <label for="email">Password</label>
        <?php echo $this->tag->textField("password"); ?>

        <p>
        <?php echo $this->tag->submitButton("Register"); ?>
    </p>
    </p>

    <?php foreach ($users as $user => $value) { ?>
            <tr>
                <td><?php echo $value->id; ?></td>
                <td><?php // echo $value->name; ?></td>
                <td><?php  // echo $value->email; ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>